export { Document } from '@modules/document/Document';
export { Section } from '@modules/document/Section';
export { Segment } from '@modules/document/Segment';
export { Line } from '@modules/document/Line';
export { Word } from '@modules/document/Word';
export { Decoration } from '@modules/document/Decoration';
export { Letter } from '@modules/document/Letter';
export { TimeFragment } from '@modules/document/TimeFragment';
export { WordState } from '@modules/document/WordState';
export { LineState } from '@modules/document/LineState';
export { CssVariable } from '@modules/document/CssVariable';
export { CssClass } from '@modules/document/CssClass';
export { DataAttribute } from '@modules/document/DataAttribute';
export { DocumentNodeId } from '@modules/document/DocumentNodeId';
export { DocumentEditor, type SegmentReplacementPart } from '@modules/document/DocumentEditor';
export { NarrationPace } from '@modules/document/NarrationPace';
