packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  onnxruntime-node: false
  protobufjs: true
  sharp: true
overrides:
  onnxruntime-web: 1.27.0
